[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
transfer_sol = "jbeELko4ALC3Wya7nuTm3ikSdVN2sdfVdH5NNagQPKS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/apple/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
